[FIGHTER_1]
state = 1

[FIGHTER_2]
type = "Animal"
state = 1

[WEAPON]
type = "Weapon"
roles = ["FIGHTER_1"]
state = 1

[[_]]

s="""
<FIGHTER_1>

    I don't like the way you use me, {FIGHTER_2.name}!

<WEAPON.attacking@FIGHTER_2:noise/slapwhack>

    _Whack!_

<FIGHTER_2?offer=-1>

    Uuurrggh!

"""
